"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: unitree_hg.msg.dds_
  IDL file: MotorCmd_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass,field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from  unitree_dds_wrapper.idl.unitree_hand import unitree_hg

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MotorCmd_(idl.IdlStruct, typename="unitree_dds_wrapper.idl.unitree_hand.unitree_hg.msg.dds_.MotorCmd_"):
    mode: types.uint8 = field(default_factory=lambda: 1)
    q: types.float32 = field(default_factory=lambda: 0.)
    dq: types.float32 = field(default_factory=lambda: 0.)
    tau: types.float32 = field(default_factory=lambda: 0.)
    kp: types.float32 = field(default_factory=lambda: 0.)
    kd: types.float32 = field(default_factory=lambda: 0.)
    reserve: types.uint32 = field(default_factory=lambda: 0)
