"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: unitree_hg.msg.dds_
  IDL file: PressSensorState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass,field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from  unitree_dds_wrapper.idl.unitree_hand import unitree_hg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class PressSensorState_(idl.IdlStruct, typename="unitree_dds_wrapper.idl.unitree_hand.unitree_hg.msg.dds_.PressSensorState_"):
    pressure: types.array[types.float32, 12] =  field(default_factory=lambda: [0,0,0,0,0,0,0,0,0,0,0,0])
    temperature: types.array[types.float32, 12] = field(default_factory=lambda: [0,0,0,0,0,0,0,0,0,0,0,0])
    lost: types.uint32  = field(default_factory=lambda: 0)
    reserve: types.uint32 = field(default_factory=lambda: 0)


